version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: sdfengine-learning-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sdfengine_learning
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - external-network

networks:
  external-network:
    name: sdfengine-shared-net
    external: true

volumes:
  postgres-data: