version: '3.8'

services:
  app:
    build: .
    container_name: sdfengine-learning-app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      APP_NAME: "SDFEngine Learning"
      NODE_ENV: development
      DB_HOST: sdfengine-learning-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_DATABASE: sdfengine_learning
      ENABLE_LOGGING: "true"
      ENABLE_DEBUG: "true"
    command: npm start
    networks:
      - external-network

networks:
  external-network:
    external: true
    name: sdfengine-shared-net